USE BuenaCineGt;
CREATE ROLE AppUser;
GO
GRANT SELECT ON SCHEMA::dbo TO AppUser;
GO
GRANT INSERT, UPDATE ON SCHEMA::dbo TO AppUser;
Go
GRANT EXECUTE ON SCHEMA::dbo TO AppUser;
GO
ALTER ROLE AppUser ADD MEMBER CineGtAppUser;


