USE BuenaCineGt;
GO
CREATE OR ALTER PROCEDURE makeLogin 
(@USERNAME VARCHAR(100), @PASSWORD VARCHAR(300) OUTPUT, @ROLE INT OUTPUT)
AS BEGIN
	BEGIN TRANSACTION;
	BEGIN TRY
		IF EXISTS (SELECT 1 FROM AppUser WHERE Username = @USERNAME)
        BEGIN
            SELECT @PASSWORD = Pass, @ROLE = UserRole FROM AppUser WHERE Username = @USERNAME;
        END
        ELSE
        BEGIN
            RAISERROR('The username do not exists or the password is incorrect. att.db', 16, 1, @USERNAME);
            RETURN;
        END

		COMMIT;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 BEGIN
            ROLLBACK TRANSACTION; --TERMINAR LA TRANSACCION
        END
		DECLARE @MENSAJE NVARCHAR(4000)= ERROR_MESSAGE();
		DECLARE @SEVERIDAD INT = ERROR_SEVERITY();
        DECLARE @ESTADO INT = ERROR_STATE();
		RAISERROR(@MENSAJE, @SEVERIDAD, @ESTADO);
	END CATCH
END;


