USE BuenaCineGt;
GO
--SP Crear nueva sala
CREATE OR ALTER PROCEDURE NewRoom (@NOROOM INT)
AS BEGIN
	BEGIN TRANSACTION;
	BEGIN TRY
		--VERIFIACIONES
		DECLARE @VERIFICATION INT = 0;

		SELECT @VERIFICATION = COUNT(*) FROM Room 
		WHERE ID = @NOROOM

		IF @VERIFICATION > 0 BEGIN
			RAISERROR('The room: %d already exist.', 16, 1, @NOROOM);
			RETURN;
		END

		INSERT INTO Room(ID) VALUES (@NOROOM);

		DECLARE @ITERATIONS INT = 1;

		WHILE(@ITERATIONS <= 10)BEGIN
			INSERT Seat (seat, Room) VALUES
			('A'+CAST(@ITERATIONS AS VARCHAR), @NOROOM),
			('B'+CAST(@ITERATIONS AS VARCHAR), @NOROOM),
			('C'+CAST(@ITERATIONS AS VARCHAR), @NOROOM),
			('D'+CAST(@ITERATIONS AS VARCHAR), @NOROOM),
			('E'+CAST(@ITERATIONS AS VARCHAR), @NOROOM),
			('F'+CAST(@ITERATIONS AS VARCHAR), @NOROOM),
			('G'+CAST(@ITERATIONS AS VARCHAR), @NOROOM),
			('H'+CAST(@ITERATIONS AS VARCHAR), @NOROOM),
			('I'+CAST(@ITERATIONS AS VARCHAR), @NOROOM),
			('J'+CAST(@ITERATIONS AS VARCHAR), @NOROOM);

			SET @ITERATIONS = @ITERATIONS + 1;
		END;

		COMMIT;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 BEGIN
            ROLLBACK TRANSACTION; --TERMINAR LA TRANSACCION
        END
		DECLARE @MENSAJE NVARCHAR(4000)= ERROR_MESSAGE();
		DECLARE @SEVERIDAD INT = ERROR_SEVERITY();
        DECLARE @ESTADO INT = ERROR_STATE();
		RAISERROR(@MENSAJE, @SEVERIDAD, @ESTADO);
	END CATCH
END;


EXEC NewRoom @NOROOM = 1;
