USE BuenaCineGt;
GO
CREATE OR ALTER PROCEDURE cancelTicket
(@TICKETSTRANSACTIONID INT)
AS BEGIN
	BEGIN TRANSACTION;
	BEGIN TRY
		DECLARE @#SEATS INT, @MOVIESESSIONID INT;

		SELECT @#SEATS = MAX(NumberSeats) FROM TicketsTransaction
		WHERE ID = @TICKETSTRANSACTIONID

		SELECT @MOVIESESSIONID = MAX(MovieSession) FROM SeatByMovieSession
		WHERE TicketsTransaction = @TICKETSTRANSACTIONID

		UPDATE MovieSession
		SET CompromisedSeats = CompromisedSeats - @#SEATS
		WHERE ID = @MOVIESESSIONID

		UPDATE TicketsTransaction
		SET TransactionStatus = 0, ModificationDate = GETDATE()
		WHERE ID = @TICKETSTRANSACTIONID

		UPDATE SeatByMovieSession
		SET Available = 1, TicketsTransaction = NULL
		WHERE TicketsTransaction = @TICKETSTRANSACTIONID

		DECLARE @PAYMENT DECIMAL(10,2);

		SELECT @PAYMENT = Payment FROM TicketsTransaction WHERE ID = @TICKETSTRANSACTIONID

		DECLARE @IDBALANCE INT, @BALANCE DECIMAL(10,2);

		SELECT @IDBALANCE = MAX(ID) FROM BalanceLog

		SELECT @BALANCE = Balance FROM BalanceLog WHERE ID = @IDBALANCE

		SET @BALANCE = @BALANCE - @PAYMENT

		INSERT INTO BalanceLog (Balance, ModificationDatetime, BalanceType, TicketsTransaction)
		VALUES (@BALANCE, GETDATE(), 0, @TICKETSTRANSACTIONID);

		COMMIT;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 BEGIN
            ROLLBACK TRANSACTION; --TERMINAR LA TRANSACCION
        END
		DECLARE @MENSAJE NVARCHAR(4000)= ERROR_MESSAGE();
		DECLARE @SEVERIDAD INT = ERROR_SEVERITY();
        DECLARE @ESTADO INT = ERROR_STATE();
		RAISERROR(@MENSAJE, @SEVERIDAD, @ESTADO);
	END CATCH
END;

EXEC CancelTicketsTransaction 6;
